add_newline = false

format = "$hostname$python$directory$git_branch$git_status$character"

[directory]
truncation_length = 3

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[git_branch]
symbol = " "

[package]
disabled = true

[python]
format = "($virtualenv) "
detect_extensions = []
detect_files = []
detect_folders = []

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold blue"
